"use strict";
const placesToVisit = ["Turkey", "Dubai", "Malaysia", "Cairo"];
console.log("Original Order:", placesToVisit);
console.log("Alphabetical Order:", [...placesToVisit].sort());
console.log("Original Order:", placesToVisit);
console.log("Reverse Alphabetical Order:", [...placesToVisit].sort().reverse());
console.log("Order of Array Changed To Reverse", placesToVisit.reverse());
console.log("Order of Array Changed To Original", placesToVisit.reverse());
console.log("Alphabetical Order:", placesToVisit.sort());
console.log("Reverse Alphabetical Order:", placesToVisit.reverse());
