var num1 = 2;
var num2 = 4;
console.log("Is num2 greater than num1? I predict true.");
console.log(num2 > num1);
console.log("Is num2 twice than num1? I predict true.");
console.log(num1 * 2 === num2);
console.log("Is num1 half than num2? I predict true.");
console.log(num2 / 2 === num1);
console.log("Is num1 less than num2? I predict true.");
console.log(num1 < num2);
console.log("Is num1 not equal to num2? I predict true.");
console.log(num1 !== num2);
console.log("Is num1 equal to num2? I predict false.");
console.log(num1 == num2);
console.log("Is num1 twice than num2? I predict false.");
console.log(num2 * 2 === num1);
console.log("Is num2 half than num1? I predict false.");
console.log(num1 / 2 === num2);
console.log("Is num2 less than num1? I predict false.");
console.log(num2 < num1);
console.log("Is num1 not divisible to num2? I predict false.");
console.log(num2 % num1 !== 0);
